// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RecommendationService.proto

package RecommendationService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TileClickedRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TileId               string   `protobuf:"bytes,2,opt,name=tileId,proto3" json:"tileId,omitempty"`
	TileScore            float64  `protobuf:"fixed64,3,opt,name=tileScore,proto3" json:"tileScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileClickedRequest) Reset()         { *m = TileClickedRequest{} }
func (m *TileClickedRequest) String() string { return proto.CompactTextString(m) }
func (*TileClickedRequest) ProtoMessage()    {}
func (*TileClickedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{0}
}

func (m *TileClickedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileClickedRequest.Unmarshal(m, b)
}
func (m *TileClickedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileClickedRequest.Marshal(b, m, deterministic)
}
func (m *TileClickedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileClickedRequest.Merge(m, src)
}
func (m *TileClickedRequest) XXX_Size() int {
	return xxx_messageInfo_TileClickedRequest.Size(m)
}
func (m *TileClickedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TileClickedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TileClickedRequest proto.InternalMessageInfo

func (m *TileClickedRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TileClickedRequest) GetTileId() string {
	if m != nil {
		return m.TileId
	}
	return ""
}

func (m *TileClickedRequest) GetTileScore() float64 {
	if m != nil {
		return m.TileScore
	}
	return 0
}

type InitRecommendationRequest struct {
	Genres               []string `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	Categories           []string `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	Languages            []string `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRecommendationRequest) Reset()         { *m = InitRecommendationRequest{} }
func (m *InitRecommendationRequest) String() string { return proto.CompactTextString(m) }
func (*InitRecommendationRequest) ProtoMessage()    {}
func (*InitRecommendationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{1}
}

func (m *InitRecommendationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRecommendationRequest.Unmarshal(m, b)
}
func (m *InitRecommendationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRecommendationRequest.Marshal(b, m, deterministic)
}
func (m *InitRecommendationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRecommendationRequest.Merge(m, src)
}
func (m *InitRecommendationRequest) XXX_Size() int {
	return xxx_messageInfo_InitRecommendationRequest.Size(m)
}
func (m *InitRecommendationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRecommendationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRecommendationRequest proto.InternalMessageInfo

func (m *InitRecommendationRequest) GetGenres() []string {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *InitRecommendationRequest) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *InitRecommendationRequest) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

type InitRecommendationResponse struct {
	IsDone               bool     `protobuf:"varint,1,opt,name=isDone,proto3" json:"isDone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRecommendationResponse) Reset()         { *m = InitRecommendationResponse{} }
func (m *InitRecommendationResponse) String() string { return proto.CompactTextString(m) }
func (*InitRecommendationResponse) ProtoMessage()    {}
func (*InitRecommendationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{2}
}

func (m *InitRecommendationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRecommendationResponse.Unmarshal(m, b)
}
func (m *InitRecommendationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRecommendationResponse.Marshal(b, m, deterministic)
}
func (m *InitRecommendationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRecommendationResponse.Merge(m, src)
}
func (m *InitRecommendationResponse) XXX_Size() int {
	return xxx_messageInfo_InitRecommendationResponse.Size(m)
}
func (m *InitRecommendationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRecommendationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitRecommendationResponse proto.InternalMessageInfo

func (m *InitRecommendationResponse) GetIsDone() bool {
	if m != nil {
		return m.IsDone
	}
	return false
}

type GetRecommendationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecommendationRequest) Reset()         { *m = GetRecommendationRequest{} }
func (m *GetRecommendationRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecommendationRequest) ProtoMessage()    {}
func (*GetRecommendationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{3}
}

func (m *GetRecommendationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecommendationRequest.Unmarshal(m, b)
}
func (m *GetRecommendationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecommendationRequest.Marshal(b, m, deterministic)
}
func (m *GetRecommendationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecommendationRequest.Merge(m, src)
}
func (m *GetRecommendationRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecommendationRequest.Size(m)
}
func (m *GetRecommendationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecommendationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecommendationRequest proto.InternalMessageInfo

func (m *GetRecommendationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type TileClickedResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileClickedResponse) Reset()         { *m = TileClickedResponse{} }
func (m *TileClickedResponse) String() string { return proto.CompactTextString(m) }
func (*TileClickedResponse) ProtoMessage()    {}
func (*TileClickedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{4}
}

func (m *TileClickedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileClickedResponse.Unmarshal(m, b)
}
func (m *TileClickedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileClickedResponse.Marshal(b, m, deterministic)
}
func (m *TileClickedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileClickedResponse.Merge(m, src)
}
func (m *TileClickedResponse) XXX_Size() int {
	return xxx_messageInfo_TileClickedResponse.Size(m)
}
func (m *TileClickedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TileClickedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TileClickedResponse proto.InternalMessageInfo

func (m *TileClickedResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MovieTile struct {
	RefId                string    `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Posters              *POSTERS  `protobuf:"bytes,2,opt,name=posters,proto3" json:"posters,omitempty"`
	Content              *CONTENT  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata             *METADATA `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MovieTile) Reset()         { *m = MovieTile{} }
func (m *MovieTile) String() string { return proto.CompactTextString(m) }
func (*MovieTile) ProtoMessage()    {}
func (*MovieTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{5}
}

func (m *MovieTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieTile.Unmarshal(m, b)
}
func (m *MovieTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieTile.Marshal(b, m, deterministic)
}
func (m *MovieTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieTile.Merge(m, src)
}
func (m *MovieTile) XXX_Size() int {
	return xxx_messageInfo_MovieTile.Size(m)
}
func (m *MovieTile) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieTile.DiscardUnknown(m)
}

var xxx_messageInfo_MovieTile proto.InternalMessageInfo

func (m *MovieTile) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *MovieTile) GetPosters() *POSTERS {
	if m != nil {
		return m.Posters
	}
	return nil
}

func (m *MovieTile) GetContent() *CONTENT {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MovieTile) GetMetadata() *METADATA {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type METADATA struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *METADATA) Reset()         { *m = METADATA{} }
func (m *METADATA) String() string { return proto.CompactTextString(m) }
func (*METADATA) ProtoMessage()    {}
func (*METADATA) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{6}
}

func (m *METADATA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_METADATA.Unmarshal(m, b)
}
func (m *METADATA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_METADATA.Marshal(b, m, deterministic)
}
func (m *METADATA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_METADATA.Merge(m, src)
}
func (m *METADATA) XXX_Size() int {
	return xxx_messageInfo_METADATA.Size(m)
}
func (m *METADATA) XXX_DiscardUnknown() {
	xxx_messageInfo_METADATA.DiscardUnknown(m)
}

var xxx_messageInfo_METADATA proto.InternalMessageInfo

func (m *METADATA) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type POSTERS struct {
	Landscape            []string `protobuf:"bytes,1,rep,name=landscape,proto3" json:"landscape,omitempty"`
	Portrait             []string `protobuf:"bytes,2,rep,name=portrait,proto3" json:"portrait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTERS) Reset()         { *m = POSTERS{} }
func (m *POSTERS) String() string { return proto.CompactTextString(m) }
func (*POSTERS) ProtoMessage()    {}
func (*POSTERS) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{7}
}

func (m *POSTERS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTERS.Unmarshal(m, b)
}
func (m *POSTERS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTERS.Marshal(b, m, deterministic)
}
func (m *POSTERS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTERS.Merge(m, src)
}
func (m *POSTERS) XXX_Size() int {
	return xxx_messageInfo_POSTERS.Size(m)
}
func (m *POSTERS) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTERS.DiscardUnknown(m)
}

var xxx_messageInfo_POSTERS proto.InternalMessageInfo

func (m *POSTERS) GetLandscape() []string {
	if m != nil {
		return m.Landscape
	}
	return nil
}

func (m *POSTERS) GetPortrait() []string {
	if m != nil {
		return m.Portrait
	}
	return nil
}

type CONTENT struct {
	DetailPage           bool     `protobuf:"varint,2,opt,name=detailPage,proto3" json:"detailPage,omitempty"`
	Package              string   `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CONTENT) Reset()         { *m = CONTENT{} }
func (m *CONTENT) String() string { return proto.CompactTextString(m) }
func (*CONTENT) ProtoMessage()    {}
func (*CONTENT) Descriptor() ([]byte, []int) {
	return fileDescriptor_abcf9f213a14e9af, []int{8}
}

func (m *CONTENT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CONTENT.Unmarshal(m, b)
}
func (m *CONTENT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CONTENT.Marshal(b, m, deterministic)
}
func (m *CONTENT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CONTENT.Merge(m, src)
}
func (m *CONTENT) XXX_Size() int {
	return xxx_messageInfo_CONTENT.Size(m)
}
func (m *CONTENT) XXX_DiscardUnknown() {
	xxx_messageInfo_CONTENT.DiscardUnknown(m)
}

var xxx_messageInfo_CONTENT proto.InternalMessageInfo

func (m *CONTENT) GetDetailPage() bool {
	if m != nil {
		return m.DetailPage
	}
	return false
}

func (m *CONTENT) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func init() {
	proto.RegisterType((*TileClickedRequest)(nil), "RecommendationService.TileClickedRequest")
	proto.RegisterType((*InitRecommendationRequest)(nil), "RecommendationService.InitRecommendationRequest")
	proto.RegisterType((*InitRecommendationResponse)(nil), "RecommendationService.InitRecommendationResponse")
	proto.RegisterType((*GetRecommendationRequest)(nil), "RecommendationService.GetRecommendationRequest")
	proto.RegisterType((*TileClickedResponse)(nil), "RecommendationService.TileClickedResponse")
	proto.RegisterType((*MovieTile)(nil), "RecommendationService.MovieTile")
	proto.RegisterType((*METADATA)(nil), "RecommendationService.METADATA")
	proto.RegisterType((*POSTERS)(nil), "RecommendationService.POSTERS")
	proto.RegisterType((*CONTENT)(nil), "RecommendationService.CONTENT")
}

func init() { proto.RegisterFile("RecommendationService.proto", fileDescriptor_abcf9f213a14e9af) }

var fileDescriptor_abcf9f213a14e9af = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4b, 0x6e, 0xdb, 0x30,
	0x10, 0x8d, 0xe2, 0xc6, 0x9f, 0xc9, 0x8e, 0x69, 0x0a, 0xd5, 0x09, 0x52, 0x43, 0xab, 0xb4, 0x8b,
	0x24, 0x75, 0xbb, 0x28, 0xd0, 0x95, 0x61, 0xbb, 0x81, 0x17, 0xf9, 0x40, 0xd6, 0xbe, 0xa0, 0xa5,
	0xb1, 0x40, 0x84, 0x26, 0x15, 0x72, 0xec, 0x13, 0xf4, 0x86, 0x3d, 0x46, 0x2f, 0x51, 0x90, 0x96,
	0x62, 0x1b, 0xb5, 0x80, 0x76, 0xd1, 0x9d, 0xde, 0xe3, 0xcc, 0xbc, 0xe1, 0xbc, 0xa1, 0xe0, 0x2c,
	0xc6, 0x54, 0x2f, 0x16, 0xa8, 0x32, 0x4e, 0x42, 0xab, 0x29, 0x9a, 0x95, 0x48, 0xf1, 0xaa, 0x30,
	0x9a, 0x34, 0x3b, 0xdd, 0x7b, 0x18, 0xcd, 0x80, 0x25, 0x42, 0xe2, 0x50, 0x8a, 0xf4, 0x09, 0xb3,
	0x18, 0x9f, 0x97, 0x68, 0x89, 0xbd, 0x81, 0xe6, 0xd2, 0xa2, 0x99, 0x64, 0x61, 0xd0, 0x0b, 0x2e,
	0x3b, 0x71, 0x89, 0x1c, 0x4f, 0x42, 0xe2, 0x24, 0x0b, 0x0f, 0xd7, 0xfc, 0x1a, 0xb1, 0x73, 0xe8,
	0xb8, 0xaf, 0x69, 0xaa, 0x0d, 0x86, 0x8d, 0x5e, 0x70, 0x19, 0xc4, 0x1b, 0x22, 0x7a, 0x86, 0xb7,
	0x13, 0x25, 0x68, 0xb7, 0x81, 0x2d, 0xa9, 0x1c, 0x95, 0x41, 0x1b, 0x06, 0xbd, 0x86, 0x2b, 0xb9,
	0x46, 0xec, 0x02, 0x20, 0xe5, 0x84, 0xb9, 0x36, 0x02, 0x6d, 0x78, 0xe8, 0xcf, 0xb6, 0x18, 0x27,
	0x29, 0xb9, 0xca, 0x97, 0x3c, 0x47, 0x1b, 0x36, 0xfc, 0xf1, 0x86, 0x88, 0x3e, 0x43, 0x77, 0x9f,
	0xa4, 0x2d, 0xb4, 0xb2, 0xe8, 0x34, 0x85, 0x1d, 0x69, 0x85, 0xfe, 0x7a, 0xed, 0xb8, 0x44, 0x51,
	0x1f, 0xc2, 0x5b, 0xac, 0xef, 0x73, 0xdf, 0x48, 0xa2, 0x6b, 0x38, 0xd9, 0x19, 0x60, 0x29, 0x11,
	0x42, 0xcb, 0x2e, 0xd3, 0x14, 0xad, 0x2d, 0x35, 0x2a, 0x18, 0xfd, 0x0c, 0xa0, 0x73, 0xa7, 0x57,
	0x02, 0x5d, 0x1a, 0x3b, 0x85, 0xa6, 0xc1, 0xf9, 0x77, 0x51, 0x95, 0x3d, 0x32, 0x38, 0x9f, 0x64,
	0xec, 0x0b, 0xb4, 0x0a, 0x6d, 0x09, 0x8d, 0xf5, 0x93, 0x3e, 0xee, 0x5f, 0x5c, 0xed, 0x37, 0xf7,
	0xf1, 0x61, 0x9a, 0x8c, 0xe3, 0x69, 0x5c, 0x85, 0xbb, 0xcc, 0x54, 0x2b, 0x42, 0x45, 0xde, 0x88,
	0xfa, 0xcc, 0xe1, 0xc3, 0x7d, 0x32, 0xbe, 0x4f, 0xe2, 0x2a, 0x9c, 0x7d, 0x85, 0xf6, 0x02, 0x89,
	0x67, 0x9c, 0x78, 0xf8, 0xca, 0xa7, 0xbe, 0xab, 0x49, 0xbd, 0x1b, 0x27, 0x83, 0xd1, 0x20, 0x19,
	0xc4, 0x2f, 0x09, 0x51, 0x0f, 0xda, 0x15, 0xcb, 0x5e, 0xc3, 0x11, 0x09, 0x92, 0x58, 0x5d, 0xc9,
	0x83, 0x68, 0x08, 0xad, 0xb2, 0xd9, 0xd2, 0xbb, 0xcc, 0xa6, 0xbc, 0xc0, 0xd2, 0xf6, 0x0d, 0xc1,
	0xba, 0xd0, 0x2e, 0xb4, 0x21, 0xc3, 0x05, 0x95, 0xbe, 0xbf, 0x60, 0x57, 0xa4, 0xec, 0xdb, 0x2d,
	0x48, 0x86, 0xc4, 0x85, 0x7c, 0xe4, 0x39, 0xfa, 0x29, 0xb5, 0xe3, 0x2d, 0xc6, 0x39, 0x50, 0xf0,
	0xf4, 0xc9, 0x1d, 0xae, 0xfb, 0xa8, 0x60, 0xff, 0x57, 0x03, 0xf6, 0xbf, 0x06, 0x36, 0x87, 0xe3,
	0x2d, 0x33, 0xd9, 0xfb, 0x9a, 0xfb, 0xff, 0xf9, 0x62, 0xba, 0x1f, 0xfe, 0x26, 0x74, 0xbd, 0x1b,
	0xd1, 0x01, 0x5b, 0xc2, 0xf9, 0x2d, 0xd2, 0x50, 0x4b, 0xc9, 0x67, 0x86, 0x93, 0x58, 0xe1, 0x37,
	0x21, 0x09, 0x8d, 0x50, 0xf9, 0x88, 0x13, 0x67, 0xd7, 0x35, 0xd5, 0xea, 0xb6, 0xb3, 0xdb, 0xab,
	0x73, 0xaa, 0x5a, 0xb4, 0xe8, 0xe0, 0x26, 0x60, 0x12, 0x4e, 0xbc, 0xac, 0xf7, 0x7b, 0xc6, 0x2d,
	0x66, 0xff, 0x53, 0xed, 0x47, 0x00, 0x67, 0xee, 0x11, 0x0a, 0x2e, 0x77, 0xc3, 0xc7, 0x2a, 0x17,
	0x0a, 0xd9, 0x4d, 0x4d, 0x95, 0xda, 0x7f, 0x45, 0xf7, 0xe3, 0x3f, 0x64, 0x54, 0xb3, 0x9e, 0x35,
	0xfd, 0xff, 0xef, 0xd3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x9a, 0x84, 0x57, 0x1e, 0x05,
	0x00, 0x00,
}
